language: python
python:
    - "3.9"
sudo: false
cache:
    ccache: true
    directories:
        - "~/.platformio"
        - "~/.buildcache"
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio run
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
